// Auto-generated by train_kws_v4.py
#ifndef MFCC_NORM_H
#define MFCC_NORM_H

const float mfcc_mean[13] = {-242.7306f, 40.6269f, 3.7168f, 8.6707f, 2.3727f, 0.7861f, 0.6562f, 0.3749f, -0.2250f, -0.5280f, -0.9871f, 0.8825f, 0.6665f};
const float mfcc_std[13] = {101.6010f, 29.6383f, 15.3031f, 13.5784f, 10.7036f, 8.4303f, 7.6685f, 6.9899f, 5.8230f, 5.4804f, 5.2358f, 5.2482f, 5.0584f};

#endif // MFCC_NORM_H
